-- Banco de receitas do Cardápio — 75 receitas (15 por refeição × 5 refeições).
-- TODAS henrique_safe=true: SEM amendoim, SEM trigo/glúten (só polvilho, tapioca,
-- fubá/milho, arroz, mandioca, pão sem glúten), SEM banana, SEM peixe/frutos do mar,
-- SEM nozes/castanha/amêndoa/oleaginosas. Proteínas só boi ou frango.
-- Quantidades = por porção (1 pessoa). Não aplicar manualmente — usar via pipeline.

insert into receitas (nome, refeicao, categoria, elaborado, henrique_safe, ingredientes, preparo) values
  -- ===================== MERENDA (15) — fruta + carboidrato sem glúten =====================
  ('Maçã e biscoito de polvilho','merenda','fruta', false, true,
   '[{"item":"Maçã","qtd":0.12,"unidade":"kg"},{"item":"Biscoito de polvilho","qtd":0.03,"unidade":"kg"}]',
   'Lavar a maçã e servir com o biscoito de polvilho.'),
  ('Uva e pipoca','merenda','fruta', false, true,
   '[{"item":"Uva","qtd":0.08,"unidade":"kg"},{"item":"Milho de pipoca","qtd":0.02,"unidade":"kg"}]',
   'Lavar a uva; estourar a pipoca e levar em potinho.'),
  ('Pera e bolinho de tapioca','merenda','fruta', false, true,
   '[{"item":"Pera","qtd":0.12,"unidade":"kg"},{"item":"Goma de tapioca","qtd":0.03,"unidade":"kg"}]',
   'Servir a pera com um bolinho de tapioca.'),
  ('Mamão e pão de queijo','merenda','fruta', false, true,
   '[{"item":"Mamão","qtd":0.12,"unidade":"kg"},{"item":"Pão de queijo","qtd":0.04,"unidade":"kg"}]',
   'Picar o mamão em potinho e levar o pão de queijo.'),
  ('Morango e biscoito de arroz','merenda','fruta', false, true,
   '[{"item":"Morango","qtd":0.08,"unidade":"kg"},{"item":"Biscoito de arroz","qtd":0.02,"unidade":"kg"}]',
   'Lavar os morangos e servir com biscoitos de arroz.'),
  ('Melão e batata-doce assada','merenda','fruta', false, true,
   '[{"item":"Melão","qtd":0.12,"unidade":"kg"},{"item":"Batata-doce","qtd":0.08,"unidade":"kg"}]',
   'Levar o melão picado e palitos de batata-doce assada.'),
  ('Manga e biscoito de polvilho','merenda','fruta', false, true,
   '[{"item":"Manga","qtd":0.1,"unidade":"kg"},{"item":"Biscoito de polvilho","qtd":0.03,"unidade":"kg"}]',
   'Picar a manga em potinho e levar o biscoito de polvilho.'),
  ('Abacaxi e pão de queijo','merenda','fruta', false, true,
   '[{"item":"Abacaxi","qtd":0.1,"unidade":"kg"},{"item":"Pão de queijo","qtd":0.04,"unidade":"kg"}]',
   'Picar o abacaxi e levar o pão de queijo.'),
  ('Melancia e pipoca','merenda','fruta', false, true,
   '[{"item":"Melancia","qtd":0.12,"unidade":"kg"},{"item":"Milho de pipoca","qtd":0.02,"unidade":"kg"}]',
   'Picar a melancia em potinho e levar a pipoca.'),
  ('Tangerina e biscoito de arroz','merenda','fruta', false, true,
   '[{"item":"Tangerina","qtd":0.12,"unidade":"kg"},{"item":"Biscoito de arroz","qtd":0.02,"unidade":"kg"}]',
   'Descascar a tangerina em gomos e levar biscoitos de arroz.'),
  ('Goiaba e bolinho de tapioca','merenda','fruta', false, true,
   '[{"item":"Goiaba","qtd":0.1,"unidade":"kg"},{"item":"Goma de tapioca","qtd":0.03,"unidade":"kg"}]',
   'Servir a goiaba picada com um bolinho de tapioca.'),
  ('Kiwi e biscoito de polvilho','merenda','fruta', false, true,
   '[{"item":"Kiwi","qtd":0.09,"unidade":"kg"},{"item":"Biscoito de polvilho","qtd":0.03,"unidade":"kg"}]',
   'Descascar e picar o kiwi; levar o biscoito de polvilho.'),
  ('Maçã e batata-doce assada','merenda','fruta', false, true,
   '[{"item":"Maçã","qtd":0.12,"unidade":"kg"},{"item":"Batata-doce","qtd":0.08,"unidade":"kg"}]',
   'Levar a maçã e palitos de batata-doce assada.'),
  ('Uva e pão de queijo','merenda','fruta', false, true,
   '[{"item":"Uva","qtd":0.08,"unidade":"kg"},{"item":"Pão de queijo","qtd":0.04,"unidade":"kg"}]',
   'Lavar a uva e levar o pão de queijo.'),
  ('Pera e pipoca','merenda','fruta', false, true,
   '[{"item":"Pera","qtd":0.12,"unidade":"kg"},{"item":"Milho de pipoca","qtd":0.02,"unidade":"kg"}]',
   'Servir a pera picada com a pipoca em potinho.'),

  -- ===================== CAFÉ DA MANHÃ (15) =====================
  ('Ovos mexidos','cafe','completo', false, true,
   '[{"item":"Ovo","qtd":2,"unidade":"un"},{"item":"Manteiga","qtd":0.005,"unidade":"kg"}]',
   'Bater os ovos, mexer na manteiga em fogo baixo até cremosos.'),
  ('Tapioca com queijo','cafe','completo', false, true,
   '[{"item":"Goma de tapioca","qtd":0.04,"unidade":"kg"},{"item":"Queijo muçarela","qtd":0.03,"unidade":"kg"}]',
   'Hidratar a goma, fazer o disco na frigideira e rechear com queijo.'),
  ('Crepioca','cafe','completo', false, true,
   '[{"item":"Ovo","qtd":1,"unidade":"un"},{"item":"Goma de tapioca","qtd":0.03,"unidade":"kg"},{"item":"Queijo muçarela","qtd":0.02,"unidade":"kg"}]',
   'Misturar ovo e goma, fritar dos dois lados e rechear com queijo.'),
  ('Mamão com mel','cafe','fruta', false, true,
   '[{"item":"Mamão","qtd":0.15,"unidade":"kg"},{"item":"Mel","qtd":0.01,"unidade":"kg"}]',
   'Picar o mamão e regar com mel.'),
  ('Iogurte natural com morango','cafe','fruta', false, true,
   '[{"item":"Iogurte natural","qtd":0.15,"unidade":"kg"},{"item":"Morango","qtd":0.06,"unidade":"kg"}]',
   'Servir o iogurte com morangos picados.'),
  ('Pão de queijo','cafe','generico', false, true,
   '[{"item":"Pão de queijo","qtd":0.06,"unidade":"kg"}]',
   'Assar os pães de queijo até dourar.'),
  ('Vitamina de morango','cafe','bebida', false, true,
   '[{"item":"Leite","qtd":0.2,"unidade":"mL"},{"item":"Morango","qtd":0.06,"unidade":"kg"}]',
   'Bater o leite com os morangos no liquidificador.'),
  ('Omelete de queijo','cafe','completo', false, true,
   '[{"item":"Ovo","qtd":2,"unidade":"un"},{"item":"Queijo muçarela","qtd":0.03,"unidade":"kg"}]',
   'Bater os ovos, fritar e dobrar com o queijo no recheio.'),
  ('Queijo branco com mamão','cafe','fruta', false, true,
   '[{"item":"Queijo branco","qtd":0.04,"unidade":"kg"},{"item":"Mamão","qtd":0.12,"unidade":"kg"}]',
   'Servir o queijo branco em fatias com o mamão picado.'),
  ('Crepioca com frango desfiado','cafe','completo', false, true,
   '[{"item":"Ovo","qtd":1,"unidade":"un"},{"item":"Goma de tapioca","qtd":0.03,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.05,"unidade":"kg"}]',
   'Fazer a crepioca e rechear com frango cozido e desfiado.'),
  ('Mingau de fubá','cafe','completo', false, true,
   '[{"item":"Fubá","qtd":0.03,"unidade":"kg"},{"item":"Leite","qtd":0.2,"unidade":"mL"},{"item":"Açúcar","qtd":0.01,"unidade":"kg"}]',
   'Dissolver o fubá no leite frio, cozinhar mexendo até engrossar e adoçar.'),
  ('Tapioca com queijo e mel','cafe','completo', false, true,
   '[{"item":"Goma de tapioca","qtd":0.04,"unidade":"kg"},{"item":"Queijo muçarela","qtd":0.02,"unidade":"kg"},{"item":"Mel","qtd":0.01,"unidade":"kg"}]',
   'Fazer o disco de tapioca, rechear com queijo e finalizar com mel.'),
  ('Ovos mexidos com queijo','cafe','completo', false, true,
   '[{"item":"Ovo","qtd":2,"unidade":"un"},{"item":"Queijo muçarela","qtd":0.02,"unidade":"kg"}]',
   'Mexer os ovos em fogo baixo e juntar o queijo no fim.'),
  ('Vitamina de mamão','cafe','bebida', false, true,
   '[{"item":"Leite","qtd":0.2,"unidade":"mL"},{"item":"Mamão","qtd":0.1,"unidade":"kg"}]',
   'Bater o leite com o mamão no liquidificador.'),
  ('Iogurte natural com manga','cafe','fruta', false, true,
   '[{"item":"Iogurte natural","qtd":0.15,"unidade":"kg"},{"item":"Manga","qtd":0.06,"unidade":"kg"}]',
   'Servir o iogurte com manga picada.'),

  -- ===================== ALMOÇO (15) — prato completo elaborado =====================
  ('Frango grelhado com arroz e feijão','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.15,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Abobrinha","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Tempere o peito de frango com sal e alho e grelhe dos dois lados.\n2. Cozinhe o arroz e o feijão carioca.\n3. Cozinhe a cenoura e a abobrinha no vapor.\n4. Refogue a couve picada fininha.\n5. Monte a salada de alface e tomate; sirva tudo junto.'),
  ('Estrogonofe de frango sem trigo','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.15,"unidade":"kg"},{"item":"Creme de leite","qtd":0.03,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Abobrinha","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Espinafre","qtd":0.05,"unidade":"kg"}]',
   E'1. Doure o frango em cubos com cebola e alho.\n2. Junte molho de tomate e cozinhe; finalize com creme de leite.\n3. Cozinhe arroz e feijão.\n4. Cozinhe cenoura e abobrinha; refogue o espinafre.\n5. Sirva com salada de alface e tomate.'),
  ('Carne moída com legumes','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Carne moída","qtd":0.15,"unidade":"kg"},{"item":"Abobrinha","qtd":0.06,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Pepino","qtd":0.05,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Refogue a carne moída com cebola, alho e tomate.\n2. Junte cenoura e abobrinha em cubos e cozinhe até macias.\n3. Cozinhe arroz e feijão.\n4. Refogue a couve.\n5. Sirva com salada de alface e pepino.'),
  ('Frango xadrez sem trigo','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.15,"unidade":"kg"},{"item":"Pimentão","qtd":0.05,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Salteie o frango em cubos em fogo alto.\n2. Junte pimentão e cenoura em cubos; tempere com shoyu sem glúten.\n3. Cozinhe arroz e feijão.\n4. Refogue a couve.\n5. Sirva com salada de alface e tomate.'),
  ('Escondidinho de batata-doce com carne','almoco','completo', true, true,
   '[{"item":"Batata-doce","qtd":0.18,"unidade":"kg"},{"item":"Carne moída","qtd":0.15,"unidade":"kg"},{"item":"Arroz","qtd":0.05,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Espinafre","qtd":0.05,"unidade":"kg"}]',
   E'1. Cozinhe a batata-doce e faça um purê.\n2. Refogue a carne moída com cebola, alho e tomate.\n3. Monte camadas de carne e purê e leve ao forno para gratinar.\n4. Cozinhe arroz, feijão e cenoura; refogue o espinafre.\n5. Sirva com salada de alface e tomate.'),
  ('Almôndegas ao molho de tomate','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Carne moída","qtd":0.15,"unidade":"kg"},{"item":"Tomate","qtd":0.06,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Abobrinha","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Tempere a carne moída e modele as almôndegas.\n2. Doure as almôndegas e cozinhe no molho de tomate.\n3. Cozinhe arroz e feijão.\n4. Cozinhe cenoura e abobrinha; refogue a couve.\n5. Sirva com salada de alface.'),
  ('Frango ensopado com legumes','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (coxa e sobrecoxa)","qtd":0.16,"unidade":"kg"},{"item":"Batata","qtd":0.07,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Doure os pedaços de frango com cebola e alho.\n2. Junte batata e cenoura em cubos e água; cozinhe até macias.\n3. Cozinhe arroz e feijão.\n4. Refogue a couve.\n5. Sirva com salada de alface e tomate.'),
  ('Bife acebolado com purê','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Patinho (bife)","qtd":0.15,"unidade":"kg"},{"item":"Batata","qtd":0.1,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Espinafre","qtd":0.05,"unidade":"kg"}]',
   E'1. Grelhe os bifes e cubra com cebola refogada.\n2. Cozinhe a batata e faça o purê com leite e manteiga.\n3. Cozinhe arroz, feijão e cenoura.\n4. Refogue o espinafre.\n5. Sirva com salada de alface e tomate.'),
  ('Frango à parmegiana sem glúten','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.15,"unidade":"kg"},{"item":"Farinha de milho (flocão)","qtd":0.02,"unidade":"kg"},{"item":"Queijo muçarela","qtd":0.03,"unidade":"kg"},{"item":"Tomate","qtd":0.06,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"}]',
   E'1. Empane o filé de frango em ovo e farinha de milho; frite.\n2. Cubra com molho de tomate e queijo e gratine.\n3. Cozinhe arroz, feijão e cenoura.\n4. Refogue a couve.\n5. Sirva com salada de alface.'),
  ('Picadinho de carne com legumes','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Coxão mole (cubos)","qtd":0.15,"unidade":"kg"},{"item":"Batata","qtd":0.07,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Refogue a carne em cubos com cebola, alho e tomate.\n2. Junte batata e cenoura; cozinhe no caldo até macias.\n3. Cozinhe arroz e feijão.\n4. Refogue a couve.\n5. Sirva com salada de alface e tomate.'),
  ('Frango com quiabo','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (coxa e sobrecoxa)","qtd":0.16,"unidade":"kg"},{"item":"Quiabo","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Doure o frango com cebola e alho.\n2. Junte o quiabo e o tomate; cozinhe até macio.\n3. Cozinhe arroz, feijão e cenoura.\n4. Refogue a couve.\n5. Sirva com salada de alface.'),
  ('Carne de panela com mandioca','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Acém (cubos)","qtd":0.15,"unidade":"kg"},{"item":"Mandioca","qtd":0.1,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Espinafre","qtd":0.05,"unidade":"kg"}]',
   E'1. Refogue a carne com cebola, alho e tomate e cozinhe na pressão até macia.\n2. Cozinhe a mandioca em pedaços até amaciar.\n3. Cozinhe arroz, feijão e cenoura.\n4. Refogue o espinafre.\n5. Sirva com salada de alface.'),
  ('Frango assado com batata','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (coxa e sobrecoxa)","qtd":0.16,"unidade":"kg"},{"item":"Batata","qtd":0.1,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Tempere o frango com alho e limão e asse com batata e cenoura.\n2. Cozinhe arroz e feijão.\n3. Refogue a couve.\n4. Monte a salada de alface e tomate.\n5. Sirva tudo junto.'),
  ('Carne moída com abóbora','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Carne moída","qtd":0.15,"unidade":"kg"},{"item":"Abóbora","qtd":0.08,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Tomate","qtd":0.05,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"}]',
   E'1. Refogue a carne moída com cebola, alho e tomate.\n2. Junte a abóbora em cubos e cozinhe até desmanchar levemente.\n3. Cozinhe arroz, feijão e cenoura.\n4. Refogue a couve.\n5. Sirva com salada de alface.'),
  ('Frango ao molho de tomate com arroz e feijão','almoco','completo', true, true,
   '[{"item":"Arroz","qtd":0.06,"unidade":"kg"},{"item":"Feijão carioca","qtd":0.05,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.15,"unidade":"kg"},{"item":"Tomate","qtd":0.06,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Abobrinha","qtd":0.06,"unidade":"kg"},{"item":"Alface","qtd":0.04,"unidade":"kg"},{"item":"Espinafre","qtd":0.05,"unidade":"kg"}]',
   E'1. Doure o frango em iscas e cozinhe no molho de tomate caseiro.\n2. Cozinhe arroz e feijão.\n3. Cozinhe cenoura e abobrinha no vapor.\n4. Refogue o espinafre.\n5. Sirva com salada de alface.'),

  -- ===================== LANCHE DA TARDE (15) =====================
  ('Iogurte natural com morango','lanche','generico', false, true,
   '[{"item":"Iogurte natural","qtd":0.15,"unidade":"kg"},{"item":"Morango","qtd":0.06,"unidade":"kg"}]',
   'Servir o iogurte com morangos picados.'),
  ('Mix de frutas','lanche','fruta', false, true,
   '[{"item":"Maçã","qtd":0.06,"unidade":"kg"},{"item":"Mamão","qtd":0.06,"unidade":"kg"},{"item":"Uva","qtd":0.05,"unidade":"kg"}]',
   'Picar e misturar as frutas em uma tigela.'),
  ('Vitamina de mamão','lanche','bebida', false, true,
   '[{"item":"Leite","qtd":0.2,"unidade":"mL"},{"item":"Mamão","qtd":0.1,"unidade":"kg"}]',
   'Bater o leite com o mamão no liquidificador.'),
  ('Queijo branco em cubos','lanche','generico', false, true,
   '[{"item":"Queijo branco","qtd":0.05,"unidade":"kg"}]',
   'Cortar o queijo branco em cubos e servir.'),
  ('Pão de queijo','lanche','generico', false, true,
   '[{"item":"Pão de queijo","qtd":0.06,"unidade":"kg"}]',
   'Assar os pães de queijo até dourar.'),
  ('Biscoito de arroz com requeijão','lanche','generico', false, true,
   '[{"item":"Biscoito de arroz","qtd":0.02,"unidade":"kg"},{"item":"Requeijão","qtd":0.02,"unidade":"kg"}]',
   'Passar o requeijão sobre os biscoitos de arroz.'),
  ('Iogurte natural com manga','lanche','fruta', false, true,
   '[{"item":"Iogurte natural","qtd":0.15,"unidade":"kg"},{"item":"Manga","qtd":0.06,"unidade":"kg"}]',
   'Servir o iogurte com manga picada.'),
  ('Vitamina de morango','lanche','bebida', false, true,
   '[{"item":"Leite","qtd":0.2,"unidade":"mL"},{"item":"Morango","qtd":0.06,"unidade":"kg"}]',
   'Bater o leite com os morangos no liquidificador.'),
  ('Biscoito de polvilho com queijo','lanche','generico', false, true,
   '[{"item":"Biscoito de polvilho","qtd":0.03,"unidade":"kg"},{"item":"Queijo branco","qtd":0.03,"unidade":"kg"}]',
   'Servir o biscoito de polvilho com fatias de queijo branco.'),
  ('Maçã com mel','lanche','fruta', false, true,
   '[{"item":"Maçã","qtd":0.12,"unidade":"kg"},{"item":"Mel","qtd":0.01,"unidade":"kg"}]',
   'Picar a maçã e regar com mel.'),
  ('Pipoca','lanche','generico', false, true,
   '[{"item":"Milho de pipoca","qtd":0.025,"unidade":"kg"},{"item":"Óleo","qtd":0.005,"unidade":"mL"}]',
   'Estourar o milho com um fio de óleo e sal.'),
  ('Batata-doce assada','lanche','generico', false, true,
   '[{"item":"Batata-doce","qtd":0.12,"unidade":"kg"}]',
   'Assar a batata-doce até macia.'),
  ('Crepioca de queijo','lanche','completo', false, true,
   '[{"item":"Ovo","qtd":1,"unidade":"un"},{"item":"Goma de tapioca","qtd":0.03,"unidade":"kg"},{"item":"Queijo muçarela","qtd":0.02,"unidade":"kg"}]',
   'Misturar ovo e goma, fritar e rechear com queijo.'),
  ('Salada de frutas com mel','lanche','fruta', false, true,
   '[{"item":"Mamão","qtd":0.06,"unidade":"kg"},{"item":"Manga","qtd":0.05,"unidade":"kg"},{"item":"Morango","qtd":0.05,"unidade":"kg"},{"item":"Mel","qtd":0.01,"unidade":"kg"}]',
   'Picar as frutas, misturar e regar com mel.'),
  ('Biscoito de arroz com queijo','lanche','generico', false, true,
   '[{"item":"Biscoito de arroz","qtd":0.02,"unidade":"kg"},{"item":"Queijo branco","qtd":0.03,"unidade":"kg"}]',
   'Servir os biscoitos de arroz com fatias de queijo.'),

  -- ===================== JANTAR (15) — fácil/leve, com preparo =====================
  ('Sopa de legumes com frango','jantar','elaborado', true, true,
   '[{"item":"Frango (peito)","qtd":0.12,"unidade":"kg"},{"item":"Batata","qtd":0.08,"unidade":"kg"},{"item":"Cenoura","qtd":0.06,"unidade":"kg"},{"item":"Abobrinha","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e o frango em cubos.\n2. Junte batata, cenoura e abobrinha picadas e cubra com água.\n3. Cozinhe até os legumes ficarem macios.\n4. Ajuste o sal e sirva quente.'),
  ('Creme de abóbora','jantar','elaborado', true, true,
   '[{"item":"Abóbora","qtd":0.2,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"},{"item":"Creme de leite","qtd":0.02,"unidade":"kg"}]',
   E'1. Refogue a cebola e junte a abóbora em cubos com água.\n2. Cozinhe até desmanchar e bata até virar creme.\n3. Volte à panela, junte o creme de leite e aqueça.\n4. Ajuste o sal e sirva.'),
  ('Canja de frango com arroz','jantar','elaborado', true, true,
   '[{"item":"Frango (peito)","qtd":0.12,"unidade":"kg"},{"item":"Arroz","qtd":0.04,"unidade":"kg"},{"item":"Cenoura","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e o frango em cubos.\n2. Junte o arroz, a cenoura e bastante água.\n3. Cozinhe até o arroz desmanchar e o caldo encorpar.\n4. Ajuste o sal e sirva quente.'),
  ('Sopa de mandioca com carne','jantar','elaborado', true, true,
   '[{"item":"Mandioca","qtd":0.18,"unidade":"kg"},{"item":"Carne moída","qtd":0.1,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"},{"item":"Cenoura","qtd":0.05,"unidade":"kg"}]',
   E'1. Cozinhe a mandioca até amaciar e bata com o caldo.\n2. Refogue a cebola, a cenoura e a carne moída.\n3. Junte o creme de mandioca à carne e cozinhe alguns minutos.\n4. Ajuste o sal e sirva quente.'),
  ('Creme de cenoura','jantar','elaborado', true, true,
   '[{"item":"Cenoura","qtd":0.2,"unidade":"kg"},{"item":"Batata","qtd":0.06,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e junte cenoura e batata em cubos com água.\n2. Cozinhe até macias e bata até virar creme.\n3. Volte à panela e aqueça, ajustando a consistência.\n4. Tempere com sal e sirva.'),
  ('Sopa de batata-doce com frango','jantar','elaborado', true, true,
   '[{"item":"Batata-doce","qtd":0.2,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.1,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Cozinhe a batata-doce até amaciar.\n2. Refogue a cebola e o frango desfiado.\n3. Bata a batata-doce com o caldo e junte o frango.\n4. Ajuste o sal e sirva quente.'),
  ('Caldo de feijão','jantar','elaborado', true, true,
   '[{"item":"Feijão carioca","qtd":0.08,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"},{"item":"Cenoura","qtd":0.04,"unidade":"kg"}]',
   E'1. Bata o feijão cozido com seu caldo.\n2. Refogue a cebola e a cenoura ralada.\n3. Junte o feijão batido e cozinhe até encorpar.\n4. Ajuste o sal e sirva quente.'),
  ('Sopa de frango com arroz e legumes','jantar','elaborado', true, true,
   '[{"item":"Frango (peito)","qtd":0.12,"unidade":"kg"},{"item":"Arroz","qtd":0.03,"unidade":"kg"},{"item":"Cenoura","qtd":0.05,"unidade":"kg"},{"item":"Abobrinha","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e o frango em cubos.\n2. Junte arroz, cenoura, abobrinha e água.\n3. Cozinhe até o arroz e os legumes ficarem macios.\n4. Ajuste o sal e sirva quente.'),
  ('Creme de abobrinha','jantar','elaborado', true, true,
   '[{"item":"Abobrinha","qtd":0.2,"unidade":"kg"},{"item":"Batata","qtd":0.06,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e junte abobrinha e batata em cubos com água.\n2. Cozinhe até macias e bata até virar creme.\n3. Volte à panela e aqueça.\n4. Tempere com sal e sirva.'),
  ('Sopa de carne com legumes','jantar','elaborado', true, true,
   '[{"item":"Carne moída","qtd":0.1,"unidade":"kg"},{"item":"Batata","qtd":0.07,"unidade":"kg"},{"item":"Cenoura","qtd":0.05,"unidade":"kg"},{"item":"Abobrinha","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Refogue a cebola e a carne moída.\n2. Junte batata, cenoura e abobrinha picadas e cubra com água.\n3. Cozinhe até os legumes amaciarem.\n4. Ajuste o sal e sirva quente.'),
  ('Caldo verde sem glúten','jantar','elaborado', true, true,
   '[{"item":"Batata","qtd":0.18,"unidade":"kg"},{"item":"Couve","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Cozinhe a batata com a cebola até amaciar e bata até virar creme.\n2. Volte à panela e aqueça.\n3. Junte a couve cortada bem fininha e cozinhe 2 minutos.\n4. Ajuste o sal e sirva quente.'),
  ('Creme de milho','jantar','elaborado', true, true,
   '[{"item":"Milho verde","qtd":0.15,"unidade":"kg"},{"item":"Batata","qtd":0.05,"unidade":"kg"},{"item":"Leite","qtd":0.1,"unidade":"mL"},{"item":"Cebola","qtd":0.02,"unidade":"kg"}]',
   E'1. Refogue a cebola e junte o milho, a batata e o leite.\n2. Cozinhe e bata até virar creme.\n3. Coe se quiser mais liso e aqueça novamente.\n4. Ajuste o sal e sirva.'),
  ('Sopa de abóbora com frango','jantar','elaborado', true, true,
   '[{"item":"Abóbora","qtd":0.18,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.1,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Cozinhe a abóbora e bata com o caldo.\n2. Refogue a cebola e o frango desfiado.\n3. Junte o creme de abóbora ao frango e aqueça.\n4. Ajuste o sal e sirva quente.'),
  ('Sopa de ervilha','jantar','elaborado', true, true,
   '[{"item":"Ervilha seca","qtd":0.08,"unidade":"kg"},{"item":"Cenoura","qtd":0.05,"unidade":"kg"},{"item":"Batata","qtd":0.05,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Cozinhe a ervilha seca com cenoura e batata até desmanchar.\n2. Refogue a cebola à parte.\n3. Bata a sopa até ficar cremosa e volte à panela com a cebola.\n4. Ajuste o sal e sirva quente.'),
  ('Creme de espinafre com frango','jantar','elaborado', true, true,
   '[{"item":"Espinafre","qtd":0.08,"unidade":"kg"},{"item":"Batata","qtd":0.1,"unidade":"kg"},{"item":"Frango (peito)","qtd":0.1,"unidade":"kg"},{"item":"Cebola","qtd":0.03,"unidade":"kg"}]',
   E'1. Cozinhe a batata e bata com o espinafre até virar creme.\n2. Refogue a cebola e o frango desfiado.\n3. Junte o creme ao frango e aqueça.\n4. Ajuste o sal e sirva quente.')
on conflict do nothing;
